#!/bin/bash -l

echo "Getting installer"
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
echo "Running Conda Installer"
./Miniconda3-latest-Linux-x86_64.sh && rm ./Miniconda3-latest-Linux-x86_64.sh
echo "Done"
exit 0

